Repository THChen2002/Bigdata-Line-Bot, pull requests merged in 2024-11, with the labels that each got.

#83 LINEBOTPJ-114 設備租借改使用表單
  liff_app.py
  task.py
  template.py
  templates/liff/rent.html
Labels: feature

#85 LINEBOTPJ-121 微學程修課進度查詢 Code
  app.py
  liff_app.py
  map.py
  task.py
  template.py
  templates/liff/userinfo.html
Labels: feature, spreadsheet

#87 LINEBOTPJ-125 歷史答題個人錯題報錯
  task.py
Labels: bugfix
