Repository THChen2002/Bigdata-Line-Bot, pull requests merged in 2024-07, with the labels that each got.

#22 LINEBOTPJ-56 記錄時間戳記欄位
  api/spreadsheet.py
Labels: feature

#23 LINEBOTPJ-56 記錄時間戳記欄位
  api/spreadsheet.py
Labels: bugfix

#24 LINEBOTPJ-64 更改FireStore查詢語法
  api/firebase.py
  task.py
Labels: feature

#30 LINEBOTPJ-67 重構RichMenuHelper
  api/linebot_helper.py
  app.py
Labels: refactor

#28 LINEBOTPJ-66 設計Line Notify連動頁面
  templates/base.html
  templates/notify/callback.html
  templates/notify/error.html
  templates/notify/register.html
Labels: feature

#32 LINEBOTPJ-76 Richmenu生成錯誤
  api/linebot_helper.py
Labels: bugfix
