Repository THChen2002/Bigdata-Line-Bot, pull requests merged in 2024-09, with the labels that each got.

#58 LINEBOTPJ-94 切換圖文選單會顯示等待動畫
  app.py
Labels: bugfix

#59 LINEBOTPJ-96 知識測驗TestCase
  tests/test_quiz.py
Labels: Test

#56 LINEBOTPJ-89 限時測驗
  api/linebot_helper.py
  api/spreadsheet.py
  line_notify_app.py
  task.py
Labels: feature, spreadsheet

#60 LINEBOTPJ-97 排行榜
  api/linebot_helper.py
  task.py
Labels: feature

#61 LINEBOTPJ-102 知識測驗 排行榜遮罩
  task.py
  tests/test_quiz.py
Labels: feature

#62 LINEBOTPJ-101 手動更新使用者資訊
  api/spreadsheet.gs
Labels: feature, spreadsheet

#65 LINEBOTPJ-108 問題回報
  Google Apps Script/Config.gs
  Google Apps Script/LineMessagingAPI.gs
  Google Apps Script/LineNotify.gs
  Google Apps Script/Report.gs
  Google Apps Script/Utility.gs
  api/spreadsheet.gs
  config.py
  line_notify_app.py
Labels: feature, spreadsheet, Google Apps Scripts

#66 Linebotpj 103 狀態為FALSE手動更新使用者資訊會把資料清空
  Google Apps Script/Config.gs
  Google Apps Script/LineMessagingAPI.gs
Labels: feature, Google Apps Scripts

#67 LINEBOTPJ-109 維修中提示
  api/linebot_helper.py
  app.py
  map.py
Labels: feature

#69 LINEBOTPJ-110 設定個人資訊
  api/spreadsheet.py
  app.py
  config.py
  liff_app.py
  line_notify_app.py
  map.py
  template.py
  templates/liff/liff.html
  templates/liff/userinfo.html
Labels: feature, spreadsheet, env

#71 LINEBOTPJ-70 FAQ Code
  app.py
  map.py
  task.py
  template.py
Labels: feature, spreadsheet

#72 LINEBOTPJ-67 重構RichMenuHelper
  api/linebot_helper.py
Labels: feature

#73 LINEBOTPJ-107 發生錯誤時發送通知到群組
  app.py
  config.py
Labels: feature, env

#74 LINEBOTPJ-97 修正限時測驗結果
  task.py
Labels: bugfix

#75 LINEBOTPJ-115 課程諮詢建議
  config.py
  map.py
  task.py
  template.py
Labels: feature

#76 LINEBOTPJ-70 啟用FAQ功能
  config.py
Labels: feature

#77 LINEBOTPJ-116 修正個人資料表單
  liff_app.py
  templates/liff/userinfo.html
Labels: feature, spreadsheet
