Repository THChen2002/Bigdata-Line-Bot, pull requests merged in 2024-08, with the labels that each got.

#34 LINEBOTPJ-76 Richmenu生成錯誤
  api/linebot_helper.py
Labels: bugfix

#35 LINEBOTPJ-77 處裡例外錯誤
  app.py
Labels: feature

#36 LINEBOTPJ-68 回覆訊息新增Loading Animation
  app.py
  requirements.txt
Labels: feature

#40 LINEBOTPJ-68 回覆訊息新增Loading Animation
  api/linebot_helper.py
  app.py
  requirements.txt
Labels: feature

#46 LINEBOTPJ-76 Richmenu生成錯誤
  api/linebot_helper.py
Labels: bugfix

#49 LINEBOTPJ-77 處裡例外錯誤
  app.py
Labels: feature

#48 LINEBOTPJ-68 回覆訊息新增Loading Animation
  api/linebot_helper.py
  app.py
  requirements.txt
Labels: feature

#51 LINEBOTPJ-81 知識測驗
  api/linebot_helper.py
  api/spreadsheet.py
  config.py
  map.py
  task.py
  template.py
Labels: feature

#52 LINEBOTPJ-88 使用者不可以重複作答
  task.py
Labels: feature

#55 LINEBOTPJ-90 重構create_carousel_bubbles
  api/linebot_helper.py
  map.py
  task.py
Labels: refactor

#54 LINEBOTPJ-85 user_info紀錄使用者所有資訊
  api/linebot_helper.py
Labels: feature, spreadsheet

#57 LINEBOTPJ-91 程式若在發送訊息時出錯不會顯示錯誤訊息
  api/linebot_helper.py
Labels: bugfix
